### ISSUE TITLE
DoH failing with "502 Bad Gateway"

### ISSUE THREAD

**Issue by ghost** [DigitaleGesellschaft/DNS-Resolver#26]
Servers ending with 42 only, the ones with 43 are ok.

**Comment by ryru** [comment]
Are you still facing problems? Can not see an issue when querying manually:

```
curl -v --doh-url https://dns1.digitale-gesellschaft.ch/dns-query https://www.example.com --resolve dns1.digitale-gesellschaft.ch:443:185.95.218.42
curl -v --doh-url https://dns1.digitale-gesellschaft.ch/dns-query https://www.example.com --resolve dns1.digitale-gesellschaft.ch:443:2a05:fc84::42
curl -v --doh-url https://dns2.digitale-gesellschaft.ch/dns-query https://www.example.com --resolve dns2.digitale-gesellschaft.ch:443:185.95.218.43
curl -v --doh-url https://dns2.digitale-gesellschaft.ch/dns-query https://www.example.com --resolve dns2.digitale-gesellschaft.ch:443:2a05:fc84::43
```

What software and configuration do you use to connect to our DNS resolvers?

**Comment by ryru** [comment]
We haven't changed anything recently.

DNSCrypt is not supported. See also FAQ #9: https://github.com/DigitaleGesellschaft/DNS-Resolver/blob/master/FAQ.md

**Comment by ryru** [comment]
Hm, at first glance, everything looks good and as usual. My time is a bit short right now. I triggered a reboot on both systems. I try to find some hints in the logs later this day.

Can you retest?

**Comment by ryru** [comment]
Good to know it's working for you again.

I see an increased request list size on unbound only on dns1. The data of the last days (approximately from April 6) show increased query drops because the list is too full. dns2 looks good and normal. This matches your problem description but it is hard to say if this is related.

We are currently planning a DNS resolver server upgrade in the next weeks - this should provide more load capacity for the next years.

I suggest closing this issue. If the problem should arise again, simply reopen it.
